stages:
  - clean
  - compile
  - test
  - install

before_script:
  - echo "Restoring Packages..."
clean_job:
  stage: clean
  script:
  - echo "Clean run..."
  - mvn clean
  except:
  - tags

compile_job:
  stage: compile
  script:
  - echo "Compile run..."
  - mvn compile
  except:
  - tags

test_job:
  stage: test
  script:
  - echo "Tests run..."
  - mvn test

install_job:
  stage: install
  script:
  - echo "Install run..."
  - mvn install